### ISSUE TITLE
Navigation on Android TV

### ISSUE THREAD

**Issue by slithy** [proog128/SharedPhotos#2]
Hi,

Very nice app! I installed it on Android TV, it works well except for the following issue:

Android TV requires navigation with a controller instead of a touchscreen. This does work in SharedPhotos, except there is no indication of which item is in focus. This means that navigating to a folder requires some guesswork and is a bit hit-and-miss. Indicating which folder is in focus in the navigation screen would fix the issue.

See also [design guidelines for Android TV](https://designguidelines.withgoogle.com/android-tv/system-overview/navigation.html)).

**Comment by proog128** [comment]
I never tried it on Android TV, I am surprised to hear that it works so well. I will see what I can do to make the navigation work.

**Comment by proog128** [comment]
New relase version 1.5 with a few tweaks for Android TV: [Download Shared Photos v1.5](http://www.tobiashaeussler.com/files/SharedPhotos-1.5.apk). Please let me know if it works for you. I tested it only on a Fire TV stick.
